spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootex
    password: bootex
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
